'use client'

import React, { useState, useEffect } from 'react'
import { useParams } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { formatCurrency } from '@/lib/tax-calculations'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, ArrowSquareOut, PaperPlaneTilt, CheckCircle, PencilSimple, Bell, X, Clock, LinkSimple, Lock } from '@phosphor-icons/react'
import type { Invoice, InvoiceLineItem, InvoiceActivity, ChaseEntry } from '@/types/database'

function Badge({ status }: { status: string }) {
  const map: Record<string, string> = {
    draft:     'bg-surface-sunken text-text-secondary border border-border-default',
    sent:      'bg-forest-50 text-forest-700 border border-forest-200',
    paid:      'bg-success-50 text-success-700 border border-success-200',
    overdue:   'bg-danger-50 text-danger-700 border border-danger-200',
    cancelled: 'bg-surface-sunken text-text-muted border border-border-default',
  }
  return (
    <span className={`inline-flex items-center px-2.5 py-1 rounded-xl text-sm font-semibold ${map[status] ?? 'bg-surface-sunken text-text-secondary'}`}>
      {status.charAt(0).toUpperCase() + status.slice(1)}
    </span>
  )
}

// ── Chase modal ────────────────────────────────────────────────────────
// ── Chase tiers ────────────────────────────────────────────────────────
type ChaseTier = 'friendly' | 'formal' | 'legal'

const TIER_META: Record<ChaseTier, { label: string; badge: string; badgeColor: string; badgeBg: string }> = {
  friendly: { label: 'Friendly Reminder',  badge: '1st',  badgeColor: '#1A5E8A', badgeBg: '#EBF4FD' },
  formal:   { label: 'Formal Notice',      badge: '2nd',  badgeColor: '#9A7B0A', badgeBg: '#FEF9E7' },
  legal:    { label: 'Legal Notice',       badge: '3rd+', badgeColor: '#C0392B', badgeBg: '#FDECEA' },
}

function getTierMessages(invoice: Invoice, businessName: string, dueDate: string, overdueDays: number): Record<ChaseTier, string> {
  const amt = formatCurrency(invoice.total)
  const num = invoice.invoice_number
  return {
    friendly: `This is an automated payment reminder generated by Freelax, your client's invoicing system.\n\nInvoice ${num} for ${amt} ${overdueDays > 0 ? `was due on ${dueDate} and is now ${overdueDays} day${overdueDays !== 1 ? 's' : ''} overdue` : `is due on ${dueDate}`}.\n\nPlease arrange payment at your earliest convenience. If you have any queries regarding this invoice, please contact ${businessName} directly.`,

    formal: `FORMAL PAYMENT NOTICE\n\nThis is a formal payment notice generated by Freelax on behalf of ${businessName}.\n\nDespite previous communication, invoice ${num} for ${amt}, due on ${dueDate}, remains unpaid (${overdueDays} day${overdueDays !== 1 ? 's' : ''} overdue).\n\nYou are formally requested to settle this outstanding balance within 7 days of receiving this notice.\n\nFailure to make payment may result in further action being taken to recover the debt. Please contact ${businessName} immediately if you are experiencing difficulties.`,

    legal: `NOTICE OF INTENDED LEGAL PROCEEDINGS\n\nThis is a formal legal notice generated by Freelax on behalf of ${businessName}.\n\nInvoice ${num} for ${amt}, due on ${dueDate}, is now ${overdueDays} day${overdueDays !== 1 ? 's' : ''} overdue. Despite previous reminders, this debt remains unpaid.\n\nPlease be advised that under the Late Payment of Commercial Debts Act 1998, statutory interest at 8% above the Bank of England base rate is now accruing on the outstanding balance.\n\nUnless payment is received in full within 7 days of this notice, ${businessName} reserves the right to:\n• Commence legal proceedings to recover the debt\n• Claim statutory interest and reasonable debt recovery costs\n• Report the matter to a debt collection agency\n\nTo avoid legal action, please make payment immediately and contact ${businessName} with confirmation.`,
  }
}

function ChaseModal({
  invoice,
  onClose,
  onSent,
}: {
  invoice: Invoice
  onClose: () => void
  onSent: (result: { emailSent: boolean; message: string; chaseCount: number }) => void
}) {
  const client       = invoice.clients
  const sender       = invoice.users
  const businessName = sender?.business_name || sender?.full_name || 'Your Business'
  const dueDate      = new Date(invoice.due_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  const overdueDays  = Math.max(0, Math.floor((Date.now() - new Date(invoice.due_date).getTime()) / 86400000))
  const chaseCount   = invoice.chase_log?.length ?? 0

  const formalAllowed = chaseCount >= 1
  const legalAllowed  = chaseCount >= 2
  const lastChasedAt  = invoice.chase_log?.[chaseCount - 1]?.chased_at
  const daysSinceLast = lastChasedAt
    ? Math.floor((Date.now() - new Date(lastChasedAt).getTime()) / 86400000)
    : null
  const cooldownDaysRemaining = daysSinceLast !== null && daysSinceLast < 7
    ? 7 - daysSinceLast
    : 0
  const onCooldown = cooldownDaysRemaining > 0

  const defaultTier: ChaseTier = chaseCount === 0 ? 'friendly' : chaseCount === 1 ? 'formal' : 'legal'
  const tierMessages = getTierMessages(invoice, businessName, dueDate, overdueDays)

  const [tier, setTier]       = useState<ChaseTier>(defaultTier)
  const [message, setMessage] = useState(tierMessages[defaultTier])
  const [sending, setSending] = useState(false)
  const [error, setError]     = useState<string | null>(null)

  function handleTierChange(t: ChaseTier) {
    setTier(t)
    setMessage(tierMessages[t])
  }

  async function handleSend() {
    setSending(true)
    setError(null)
    const res = await fetch('/api/invoices/chase', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ invoiceId: invoice.id, message, tier }),
    })
    const data = await res.json()
    setSending(false)
    if (res.ok) {
      onSent(data)
      onClose()
    } else {
      setError(data?.error || 'Could not send chase. Please try again.')
    }
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center px-4"
      style={{ background: 'rgba(0,0,0,0.45)' }}
      onClick={onClose}
    >
      <div
        className="bg-surface-card rounded-xl shadow-xl w-full max-w-lg flex flex-col"
        style={{ maxHeight: '90dvh' }}
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border-subtle flex-shrink-0">
          <div>
            <h2 className="font-semibold text-text-primary text-base">Chase invoice</h2>
            <p className="text-xs text-text-muted mt-0.5">
              {invoice.invoice_number} · {formatCurrency(invoice.total)}
              {overdueDays > 0 && <span className="text-danger-500 ml-1">· {overdueDays}d overdue</span>}
            </p>
          </div>
          <button onClick={onClose} aria-label="Close" className="p-1 rounded-full hover:bg-surface-sunken">
            <X weight="regular" className="w-4 h-4 text-text-muted" />
          </button>
        </div>

        <div className="px-6 py-5 space-y-4 overflow-y-auto flex-1 min-h-0">
          {/* Tier selector */}
          <div>
            <p className="text-xs font-medium text-text-muted mb-2">Chase level</p>
            <div className="flex gap-2">
              {(Object.keys(TIER_META) as ChaseTier[]).map(t => {
                const meta = TIER_META[t]
                const isActive = tier === t
                const locked =
                  (t === 'formal' && !formalAllowed) ||
                  (t === 'legal'  && !legalAllowed)
                const lockReason = locked
                  ? t === 'formal'
                    ? 'Send a friendly chase first'
                    : 'Needs 2 prior chases'
                  : ''
                return (
                  <button
                    key={t}
                    onClick={() => { if (!locked) handleTierChange(t) }}
                    disabled={locked}
                    title={lockReason || undefined}
                    style={{
                      flex: 1, padding: '8px 4px', borderRadius: 8,
                      cursor: locked ? 'not-allowed' : 'pointer',
                      border: `1.5px solid ${isActive ? meta.badgeColor : '#E2E8F0'}`,
                      background: isActive ? meta.badgeBg : '#fff',
                      opacity: locked ? 0.45 : 1,
                      transition: 'all 0.15s',
                    }}
                  >
                    <p style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: isActive ? meta.badgeColor : '#AAA', marginBottom: 2 }}>
                      {meta.badge}{locked ? <Lock weight="regular" className="inline w-2.5 h-2.5 ml-0.5 align-middle" /> : ''}
                    </p>
                    <p style={{ fontSize: 'var(--text-caption)', fontWeight: 600, color: isActive ? meta.badgeColor : '#666' }}>
                      {meta.label}
                    </p>
                    {locked && (
                      <p style={{ fontSize: 'var(--text-micro)', color: 'var(--text-secondary)', marginTop: 2 }}>{lockReason}</p>
                    )}
                  </button>
                )
              })}
            </div>
            {tier === 'legal' && (
              <p className="text-xs text-danger-600 mt-2 bg-danger-50 border border-danger-200 rounded-xl px-3 py-2">
                ⚖️ This notice references the <strong>Late Payment of Commercial Debts Act 1998</strong> and warns of legal proceedings. Only use when you intend to escalate.
              </p>
            )}
          </div>

          {/* To field */}
          <div className="flex items-center gap-2 text-sm">
            <span className="text-text-secondary w-8">To</span>
            <span className="font-medium text-text-secondary">
              {client?.contact_name || client?.name}
              {client?.email && <span className="text-text-secondary font-normal ml-1">&lt;{client.email}&gt;</span>}
            </span>
          </div>

          {/* Subject preview */}
          <div className="flex items-start gap-2 text-sm">
            <span className="text-text-secondary w-8 pt-0.5">Re</span>
            <span className="text-text-muted text-xs bg-surface-sunken px-2 py-1 rounded">
              {tier === 'legal' ? 'Notice of Intended Legal Proceedings' : tier === 'formal' ? 'Formal Payment Notice' : 'Payment Reminder'}: Invoice {invoice.invoice_number} — {formatCurrency(invoice.total)}
            </span>
          </div>

          {/* Editable message body */}
          <div>
            <label className="block text-xs font-medium text-text-muted mb-1.5">Message</label>
            <textarea
              aria-label="Message"
              value={message}
              onChange={e => setMessage(e.target.value)}
              rows={7}
              className="w-full px-3 py-2.5 border border-border-default rounded-md text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-primary/20 resize-none leading-relaxed"
            />
            <p className="text-xs text-text-secondary mt-1">
              Bank details and invoice summary will be appended automatically.
            </p>
          </div>

          {/* Bank details notice */}
          {sender?.bank_sort_code && (
            <div className="bg-surface-sunken rounded-xl px-4 py-3 text-xs text-text-muted border border-border-subtle">
              <p className="font-medium text-text-secondary mb-1">Payment details included automatically</p>
              <p>Account: <span className="font-medium text-text-secondary">{sender.bank_account_name || businessName}</span></p>
              <p>Sort code: <span className="font-medium text-text-secondary">{sender.bank_sort_code}</span> · Account: <span className="font-medium text-text-secondary">{sender.bank_account_number}</span></p>
            </div>
          )}

          {!client?.email && (
            <div className="bg-warning-50 border border-warning-200 rounded-xl px-4 py-3 text-xs text-warning-800">
              No email address on file for this client. Chase will be logged but no email will be sent.
            </div>
          )}

          {onCooldown && (
            <div className="bg-warning-50 border border-warning-200 rounded-xl px-4 py-3 text-xs text-warning-800">
              You can chase this invoice again in <strong>{cooldownDaysRemaining} day{cooldownDaysRemaining === 1 ? '' : 's'}</strong>. To prevent spam, Freelax enforces a 7-day gap between chases.
            </div>
          )}

          {error && (
            <div className="bg-danger-50 border border-danger-200 rounded-xl px-4 py-3 text-xs text-danger-700">
              {error}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between px-6 py-4 border-t border-border-subtle gap-3 flex-shrink-0">
          <button
            onClick={onClose}
            className="px-4 py-2 border border-border-default rounded-xl text-sm text-text-secondary hover:bg-surface-sunken"
          >
            Cancel
          </button>
          <button
            onClick={handleSend}
            disabled={sending || !message.trim() || onCooldown}
            style={{
              background: tier === 'legal' ? '#C0392B' : tier === 'formal' ? '#9A7B0A' : '#111',
              opacity: (sending || !message.trim() || onCooldown) ? 0.5 : 1,
            }}
            className="flex items-center gap-2 px-5 py-2 text-white rounded-xl text-sm font-medium disabled:opacity-50 transition-colors"
          >
            <Bell weight="regular" className="w-3.5 h-3.5" />
            {sending
              ? 'Sending...'
              : onCooldown
                ? `Wait ${cooldownDaysRemaining}d`
                : client?.email
                  ? `Send ${TIER_META[tier].label}`
                  : 'Log chase'}
          </button>
        </div>
      </div>
    </div>
  )
}

// ── Activity log config ────────────────────────────────────────────────
function activityConfig(entry: InvoiceActivity): {
  Icon: React.ElementType; bg: string; iconColor: string; label: string; sub?: string
} {
  const m = (entry.metadata ?? {}) as Record<string, unknown>
  switch (entry.action) {
    case 'sent':
      return {
        Icon: PaperPlaneTilt, bg: 'bg-forest-50', iconColor: 'text-forest-600',
        label: m.emailSent ? `Sent to ${m.clientEmail}` : 'Marked as sent',
        sub:   !m.emailSent ? 'No email sent — add a client email or Resend API key' : undefined,
      }
    case 'paid':
      return {
        Icon: CheckCircle, bg: 'bg-success-50', iconColor: 'text-success-600',
        label: 'Marked as paid',
        sub:   typeof m.paidDate === 'string'
          ? `Paid date: ${new Date(m.paidDate).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}`
          : undefined,
      }
    case 'chased': {
      const tierLabel = m.tier === 'legal' ? 'Legal Notice' : m.tier === 'formal' ? 'Formal Notice' : 'Friendly Reminder'
      return {
        Icon: Bell, bg: 'bg-warning-50', iconColor: 'text-amber-500',
        label: `Chased — ${tierLabel}`,
        sub:   m.emailSent ? `Email sent to ${m.clientEmail}` : 'No email sent',
      }
    }
    case 'status_changed':
      return {
        Icon: ArrowRight, bg: 'bg-surface-sunken', iconColor: 'text-text-secondary',
        label: `Status changed to ${m.to ? (m.to as string).charAt(0).toUpperCase() + (m.to as string).slice(1) : m.to}`,
        sub:   m.from ? `Previous status: ${m.from}` : undefined,
      }
    case 'overdue':
      return {
        Icon: Clock, bg: 'bg-danger-50', iconColor: 'text-danger-500',
        label: 'Marked as overdue',
      }
    default:
      return {
        Icon: Clock, bg: 'bg-surface-sunken', iconColor: 'text-text-secondary',
        label: entry.action,
      }
  }
}

// ── Main page ──────────────────────────────────────────────────────────
export default function InvoiceDetailPage() {
  const params = useParams<{ id: string }>()
  const [invoice, setInvoice] = useState<Invoice | null>(null)
  const [activity, setActivity] = useState<InvoiceActivity[]>([])
  const [loading, setLoading]  = useState(true)
  const [sending, setSending]  = useState(false)
  const [marking, setMarking]  = useState(false)
  const [chaseOpen, setChaseOpen] = useState(false)
  const [msg, setMsg]             = useState<{ type: 'success' | 'error'; text: string } | null>(null)
  const [payLink, setPayLink]     = useState<string | null>(null)
  const [copyingLink, setCopyingLink] = useState(false)

  async function load() {
    const supabase = createClient()
    const [{ data: inv }, { data: acts }] = await Promise.all([
      supabase
        .from('invoices')
        .select('*, clients(*), projects(title), invoice_line_items(*), users(*)')
        .eq('id', params.id)
        .single(),
      supabase
        .from('invoice_activity')
        .select('*')
        .eq('invoice_id', params.id)
        .order('created_at', { ascending: true }),
    ])
    setInvoice(inv)
    setActivity(acts ?? [])
    setLoading(false)
  }

  useEffect(() => { load() }, [params.id])

  async function handleSend() {
    setSending(true)
    const res = await fetch('/api/invoices/send', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ invoiceId: params.id }),
    })
    setSending(false)
    if (res.ok) { setMsg({ type: 'success', text: 'Invoice sent successfully' }); load() }
    else { const d = await res.json(); setMsg({ type: 'error', text: d.error ?? 'Failed to send' }) }
    setTimeout(() => setMsg(null), 4000)
  }

  async function getPaymentLink() {
    setCopyingLink(true)
    try {
      const res  = await fetch('/api/invoices/public-token', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ invoiceId: params.id }),
      })
      const data = await res.json()
      if (data.url) {
        setPayLink(data.url)
        await navigator.clipboard.writeText(data.url)
        setMsg({ type: 'success', text: '✓ Payment link copied to clipboard' })
        setTimeout(() => setMsg(null), 4000)
      }
    } catch (e) { console.error(e) }
    setCopyingLink(false)
  }

  async function handleMarkPaid() {
    setMarking(true)
    const res = await fetch('/api/invoices/mark-paid', {
      method: 'POST', headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ invoiceId: params.id }),
    })
    setMarking(false)
    if (res.ok) { setMsg({ type: 'success', text: '✓ Invoice marked as paid' }); load() }
    else { setMsg({ type: 'error', text: 'Failed to mark as paid' }) }
    setTimeout(() => setMsg(null), 4000)
  }

  if (loading) return (
    <div className="space-y-4 max-w-3xl">
      {[1,2,3].map(i => <div key={i} className="h-16 bg-surface-sunken rounded-xl animate-pulse" />)}
    </div>
  )
  if (!invoice) return <p className="text-text-muted">Invoice not found.</p>

  const client    = invoice.clients
  const sender    = invoice.users
  const lineItems = invoice.invoice_line_items ?? []
  const chaseLog: ChaseEntry[] = invoice.chase_log ?? []

  const canSend    = ['draft', 'sent', 'overdue'].includes(invoice.status)
  const canChase   = ['sent', 'overdue'].includes(invoice.status)
  const canMarkPaid = ['sent', 'overdue'].includes(invoice.status)

  // Bank details
  const hasBankDetails = sender?.bank_sort_code && sender?.bank_account_number

  return (
    <div className="max-w-3xl space-y-6">
      {/* Back + header */}
      <div>
        <Link href="/invoices" className="flex items-center gap-1 text-sm text-text-muted hover:text-text-secondary mb-3">
          <ArrowLeft weight="regular" className="w-4 h-4" /> Back to invoices
        </Link>
        <div className="flex items-center justify-between flex-wrap gap-3">
          <div className="flex items-center gap-3">
            <h1 className="text-2xl font-serif font-semibold text-text-primary">{invoice.invoice_number}</h1>
            <Badge status={invoice.status} />
            {chaseLog.length > 0 && (
              <span className="flex items-center gap-1 text-xs text-warning-600 bg-warning-50 border border-warning-200 px-2 py-0.5 rounded-lg">
                <Bell weight="regular" className="w-3 h-3" /> Chased {chaseLog.length}×
              </span>
            )}
          </div>
          <div className="flex flex-wrap gap-2">
            {invoice.status === 'draft' && (
              <Link href={`/invoices/${invoice.id}/edit`} className="flex items-center gap-1.5 px-3 py-2 border border-border-default rounded-lg text-sm hover:bg-surface-sunken">
                <PencilSimple weight="regular" className="w-3.5 h-3.5" /> Edit
              </Link>
            )}
            {canSend && (
              <button onClick={handleSend} disabled={sending}
                className="flex items-center gap-1.5 px-3 py-2 bg-forest-900 text-white rounded-xl text-sm font-medium hover:bg-forest-900 disabled:opacity-50">
                <PaperPlaneTilt weight="regular" className="w-3.5 h-3.5" />
                {sending ? 'Sending...' : invoice.status === 'draft' ? 'Send invoice' : 'Resend'}
              </button>
            )}
            {canChase && (
              <button
                onClick={() => setChaseOpen(true)}
                className="flex items-center gap-1.5 px-3 py-2 bg-warning-500 text-white rounded-xl text-sm font-medium hover:bg-warning-600"
              >
                <Bell weight="regular" className="w-3.5 h-3.5" />
                Chase{chaseLog.length > 0 ? ` (${chaseLog.length})` : ''}
              </button>
            )}
            <a href={`/api/invoices/pdf?id=${invoice.id}`} target="_blank" rel="noopener noreferrer"
              className="flex items-center gap-1.5 px-3 py-2 border border-border-default rounded-xl text-sm hover:bg-surface-sunken">
              <ArrowSquareOut weight="regular" className="w-3.5 h-3.5" /> PDF
            </a>
            {invoice.status !== 'draft' && (
              <button onClick={getPaymentLink} disabled={copyingLink}
                className="flex items-center gap-1.5 px-3 py-2 border border-border-default rounded-xl text-sm hover:bg-surface-sunken disabled:opacity-50"
                title={payLink ?? 'Copy client payment link'}>
                <LinkSimple weight="regular" className="w-3.5 h-3.5" />
                {copyingLink ? 'Generating…' : 'Payment link'}
              </button>
            )}
            {canMarkPaid && invoice.status !== 'paid' && (
              <button onClick={handleMarkPaid} disabled={marking}
                className="flex items-center gap-1.5 px-4 py-2 bg-success-700 text-white rounded-xl text-sm font-semibold hover:bg-success-800 disabled:opacity-50">
                <CheckCircle weight="regular" className="w-4 h-4" />
                {marking ? 'Saving...' : 'Mark as paid'}
              </button>
            )}
            {invoice.status === 'paid' && (
              <span className="flex items-center gap-1.5 px-4 py-2 bg-success-50 text-success-700 rounded-xl text-sm font-semibold border border-success-200">
                <CheckCircle weight="regular" className="w-4 h-4" /> Paid
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Status message */}
      {msg && (
        <>
          {/* Upgrade prompt — shown for plan restriction errors */}
          {msg.type === 'error' && msg.text.toLowerCase().includes('plan') ? (
            <div className="flex items-start gap-4 px-5 py-4 rounded-xl border border-warning-200 bg-warning-50">
              <div className="flex-shrink-0 w-9 h-9 rounded-full bg-warning-100 border border-warning-200 flex items-center justify-center text-warning-600">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M8 1l1.8 4.8H15l-4 2.9 1.5 4.8L8 10.4 3.5 13.5l1.5-4.8L1 5.8h5.2L8 1z" fill="currentColor"/></svg>
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-warning-900 mb-0.5">Upgrade required</p>
                <p className="text-sm text-warning-800">{msg.text}</p>
              </div>
              <a href="/settings?tab=billing" className="flex-shrink-0 px-4 py-2 bg-warning-500 hover:bg-warning-600 text-white text-sm font-semibold rounded-lg transition-colors">
                Upgrade
              </a>
              <button onClick={() => setMsg(null)} className="flex-shrink-0 text-warning-400 hover:text-warning-600 transition-colors">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
              </button>
            </div>
          ) : (
            /* Standard success / error toast */
            <div className={`flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-medium border ${
              msg.type === 'success'
                ? 'bg-success-50 text-success-800 border-success-200'
                : 'bg-danger-50 text-danger-700 border-danger-200'
            }`}>
              {msg.type === 'success' ? (
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M3 8l4 4 6-6" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
              ) : (
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><circle cx="8" cy="8" r="6" stroke="currentColor" stroke-width="1.5"/><path d="M8 5v3.5M8 11v.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
              )}
              <span className="flex-1">{msg.text}</span>
              <button onClick={() => setMsg(null)} aria-label="Dismiss message" className="opacity-50 hover:opacity-100 transition-opacity">
                <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><path d="M3 3l8 8M11 3l-8 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
              </button>
            </div>
          )}
        </>
      )}

      {/* Invoice — Letterhead design */}
      <div className="bg-surface-card rounded-xl border border-border-default shadow-sm overflow-hidden">
        <style>{`
          @media (max-width: 640px) {
            .inv-header { flex-direction: column !important; gap: 16px !important; }
            .inv-bill-row { flex-direction: column !important; gap: 20px !important; }
            .inv-bill-dates { text-align: left !important; }
            .inv-footer-row { flex-direction: column !important; gap: 16px !important; }
            .inv-totals { width: 100% !important; }
            .inv-table th.hide-sm, .inv-table td.hide-sm { display: none; }
          }
        `}</style>

        {/* Header */}
        <div style={{ padding: '32px 40px 28px', borderBottom: '1px solid #f1f5f9' }}>
          <div className="inv-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div>
              {sender?.logo_url
                ? <img src={sender.logo_url} alt="" style={{ height: 40, objectFit: 'contain', marginBottom: 10, display: 'block' }} />
                : <p style={{ fontSize: 'var(--text-lg)', fontWeight: 600, color: 'var(--text-primary)', letterSpacing: '-0.03em', marginBottom: 4 }}>{sender?.business_name || sender?.full_name || ''}</p>
              }
              {sender?.email && <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', marginTop: 2 }}>{sender.email}</p>}
              {sender?.address_line1 && <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)' }}>{sender.address_line1}{sender?.city ? `, ${sender.city}` : ''}</p>}
              {sender?.vat_number && <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', marginTop: 2 }}>VAT: {sender.vat_number}</p>}
            </div>
            <div className="text-right">
              <p style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-muted)', marginBottom: 6 }}>Invoice</p>
              <p style={{ fontSize: 'var(--text-xl)', fontWeight: 600, color: 'var(--text-primary)', letterSpacing: '-0.03em', lineHeight: 1 }}>{invoice.invoice_number}</p>
            </div>
          </div>
        </div>

        {/* Bill to + dates */}
        <div style={{ padding: '24px 40px', borderBottom: '1px solid #f1f5f9' }}>
          <div className="inv-bill-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
            <div>
              <p style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-muted)', marginBottom: 8 }}>Bill to</p>
              <p style={{ fontSize: 'var(--text-base)', fontWeight: 600, color: 'var(--text-primary)', letterSpacing: '-0.015em', marginBottom: 3 }}>{client?.name ?? '—'}</p>
              {client?.contact_name && <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)', marginTop: 2 }}>{client.contact_name}</p>}
              {client?.email && <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-muted)' }}>{client.email}</p>}
              {client?.address_line1 && <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', marginTop: 4 }}>{client.address_line1}</p>}
              {client?.city && <p style={{ fontSize: 'var(--text-xs)', color: 'var(--text-secondary)' }}>{client.city}{client.postcode ? `, ${client.postcode}` : ''}</p>}
            </div>
            <div className="inv-bill-dates" style={{ textAlign: 'right', display: 'flex', flexDirection: 'column', gap: 10 }}>
              <div>
                <p style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-muted)', marginBottom: 3 }}>Issue date</p>
                <p style={{ fontSize: 'var(--text-sm)', fontWeight: 600, color: 'var(--text-primary)' }}>{new Date(invoice.issue_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
              </div>
              <div>
                <p style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-muted)', marginBottom: 3 }}>Due date</p>
                <p style={{ fontSize: 'var(--text-sm)', fontWeight: 600, color: invoice.status === 'overdue' ? '#dc2626' : '#0f172a' }}>{new Date(invoice.due_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
              </div>
              {invoice.paid_date && (
                <div>
                  <p style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-muted)', marginBottom: 3 }}>Paid on</p>
                  <p style={{ fontSize: 'var(--text-sm)', fontWeight: 600, color: 'var(--success-600)' }}>{new Date(invoice.paid_date).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</p>
                </div>
              )}
              <div style={{ marginTop: 4 }}>
                {invoice.status === 'paid' && <span style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--success-600)', border: '1.5px solid var(--success-600)', padding: '3px 10px' }}>Paid</span>}
                {invoice.status === 'overdue' && <span style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--danger-600)', border: '1.5px solid var(--danger-600)', padding: '3px 10px' }}>Overdue</span>}
                {invoice.status === 'draft' && <span style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-secondary)', border: '1.5px solid var(--border-default)', padding: '3px 10px' }}>Draft</span>}
              </div>
            </div>
          </div>
        </div>

        {/* Line items */}
        <div style={{ padding: '24px 40px' }}>
          <table className="inv-table w-full" style={{ borderCollapse: 'collapse', marginBottom: 24 }}>
            <thead>
              <tr style={{ borderTop: '1px solid #e2e8f0', borderBottom: '1px solid #e2e8f0' }}>
                <th style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-secondary)', padding: '9px 0', textAlign: 'left' }}>Description</th>
                <th className="hide-sm" style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-secondary)', padding: '9px 0', textAlign: 'right' }}>Qty</th>
                <th className="hide-sm" style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-secondary)', padding: '9px 0', textAlign: 'right' }}>Unit price</th>
                <th className="hide-sm" style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-secondary)', padding: '9px 0', textAlign: 'right' }}>VAT</th>
                <th style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-secondary)', padding: '9px 0', textAlign: 'right' }}>Total</th>
              </tr>
            </thead>
            <tbody>
              {lineItems.map((item: InvoiceLineItem) => (
                <tr key={item.id} style={{ borderBottom: '1px solid #f8fafc' }}>
                  <td style={{ padding: '12px 0', fontSize: 'var(--text-sm)', color: 'var(--text-body)' }}>{item.description}</td>
                  <td className="hide-sm" style={{ padding: '12px 0', fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', textAlign: 'right' }}>{item.quantity}</td>
                  <td className="hide-sm" style={{ padding: '12px 0', fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', textAlign: 'right' }}>{formatCurrency(item.unit_price)}</td>
                  <td className="hide-sm" style={{ padding: '12px 0', fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', textAlign: 'right' }}>{item.vat_rate}%</td>
                  <td style={{ padding: '12px 0', fontSize: 'var(--text-sm)', fontWeight: 600, color: 'var(--text-primary)', textAlign: 'right' }}>{formatCurrency(item.line_total)}</td>
                </tr>
              ))}
            </tbody>
          </table>

          {/* Footer row: payment details + totals */}
          <div className="inv-footer-row" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 24 }}>

            {/* Payment details */}
            {hasBankDetails ? (
              <div>
                <p style={{ fontSize: 'var(--text-micro)', fontWeight: 600, color: 'var(--text-muted)', marginBottom: 10 }}>Payment details</p>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
                  {[
                    { label: 'Account name',   value: sender.bank_account_name || sender.business_name || sender.full_name },
                    { label: 'Sort code',      value: sender.bank_sort_code },
                    { label: 'Account number', value: sender.bank_account_number },
                    { label: 'Reference',      value: sender.bank_reference_note || invoice.invoice_number },
                  ].map(r => (
                    <div key={r.label} style={{ display: 'flex', gap: 16 }}>
                      <span style={{ fontSize: 11.5, color: 'var(--text-muted)', width: 110, flexShrink: 0 }}>{r.label}</span>
                      <span style={{ fontSize: 11.5, fontWeight: 600, color: 'var(--text-body)' }}>{r.value}</span>
                    </div>
                  ))}
                </div>
                {invoice.payment_terms && <p style={{ fontSize: 'var(--text-caption)', color: 'var(--text-secondary)', marginTop: 12 }}>{invoice.payment_terms}</p>}
              </div>
            ) : (
              <div>
                {invoice.payment_terms && <p style={{ fontSize: 'var(--text-caption)', color: 'var(--text-secondary)' }}>{invoice.payment_terms}</p>}
                {invoice.notes && <p style={{ fontSize: 'var(--text-caption)', color: 'var(--text-secondary)', fontStyle: 'italic', marginTop: 4 }}>{invoice.notes}</p>}
              </div>
            )}

            {/* Totals */}
            <div className="inv-totals" style={{ width: 220, flexShrink: 0 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', borderBottom: '1px solid #f1f5f9' }}>
                <span>Subtotal</span><span style={{ color: 'var(--text-secondary)', fontWeight: 500 }}>{formatCurrency(invoice.subtotal)}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '5px 0', fontSize: 'var(--text-xs)', color: 'var(--text-secondary)', borderBottom: '1px solid #f1f5f9' }}>
                <span>VAT</span><span style={{ color: 'var(--text-secondary)', fontWeight: 500 }}>{formatCurrency(invoice.vat_amount)}</span>
              </div>
              <div style={{ display: 'flex', justifyContent: 'space-between', padding: '12px 0 0', fontSize: 'var(--text-base)', fontWeight: 600, color: 'var(--text-primary)', borderTop: '1.5px solid #0f172a', marginTop: 4 }}>
                <span>Total due</span><span>{formatCurrency(invoice.total)}</span>
              </div>
            </div>
          </div>

          {/* Notes if bank details shown */}
          {hasBankDetails && invoice.notes && (
            <p style={{ fontSize: 'var(--text-caption)', color: 'var(--text-secondary)', fontStyle: 'italic', marginTop: 20 }}>{invoice.notes}</p>
          )}

          {/* Doc footer */}
          <div style={{ marginTop: 32, paddingTop: 16, borderTop: '1px solid #f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span style={{ fontSize: 'var(--text-micro)', color: 'var(--text-secondary)' }}>{invoice.invoice_number} · {sender?.business_name || sender?.full_name || ''}</span>
            <span style={{ fontSize: 'var(--text-micro)', color: 'var(--text-secondary)' }}>Powered by Freelax</span>
          </div>
        </div>
      </div>

      {/* Activity log */}
      <div className="bg-surface-card rounded-xl border border-border-default overflow-hidden">
        <div className="px-5 py-3 border-b border-border-subtle flex items-center gap-2">
          <Clock weight="regular" className="w-4 h-4 text-text-secondary" />
          <h2 className="text-sm font-semibold text-text-primary">Activity</h2>
          {activity.length > 0 && (
            <span className="ml-auto text-xs text-text-secondary">
              {activity.length} event{activity.length !== 1 ? 's' : ''}
            </span>
          )}
        </div>
        {activity.length === 0 ? (
          <div className="px-5 py-8 text-center">
            <Clock weight="regular" className="w-6 h-6 text-text-muted mx-auto mb-2" />
            <p className="text-sm text-text-secondary">No activity recorded yet.</p>
            <p className="text-xs text-text-muted mt-1">Events will appear here when the invoice is sent, paid, or chased.</p>
          </div>
        ) : (
          <div className="divide-y divide-slate-50">
            {[...activity].reverse().map((entry: InvoiceActivity) => {
              const cfg = activityConfig(entry)
              return (
                <div key={entry.id} className="flex items-start gap-3 px-5 py-3.5">
                  <div className={`w-7 h-7 rounded-full flex items-center justify-center shrink-0 mt-0.5 ${cfg.bg}`}>
                    <cfg.Icon weight="regular" className={`w-3.5 h-3.5 ${cfg.iconColor}`} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm text-text-secondary font-medium">{cfg.label}</p>
                    {cfg.sub && <p className="text-xs text-text-secondary mt-0.5">{cfg.sub}</p>}
                  </div>
                  <p className="text-xs text-text-secondary shrink-0 pt-0.5">
                    {new Date(entry.created_at).toLocaleDateString('en-GB', {
                      day: 'numeric', month: 'short', year: 'numeric',
                    })}
                    {' '}
                    {new Date(entry.created_at).toLocaleTimeString('en-GB', {
                      hour: '2-digit', minute: '2-digit',
                    })}
                  </p>
                </div>
              )
            })}
          </div>
        )}
      </div>

      {/* Chase modal */}
      {chaseOpen && (
        <ChaseModal
          invoice={invoice}
          onClose={() => setChaseOpen(false)}
          onSent={result => {
            setMsg({ type: 'success', text: result.message })
            setTimeout(() => setMsg(null), 5000)
            load()
          }}
        />
      )}
    </div>
  )
}
